#!/bin/sh
cd ${0%/*} || exit 1 # Run from this directory

# -----------------------------
# Parse --sudo flag
# -----------------------------
SUDO_MODE=false
for arg in "$@"; do
    if [ "$arg" = "--sudo" ]; then
        SUDO_MODE=true
        # remove --sudo from arguments
        set -- $(printf '%s\n' "$@" | sed 's/--sudo//')
        break
    fi
done

# Override locations if sudo mode is enabled
if [ "$SUDO_MODE" = true ]; then
    export FOAM_USER_LIBBIN="${FOAM_LIBBIN}"
    export FOAM_USER_APPBIN="${FOAM_APPBIN}"
    echo "Running in --sudo mode: installing to system locations."
fi


# Parse arguments for library compilation
. $WM_DIR/scripts/AllwmakeParseArguments

echo "Utilising $WM_PROJECT-$WM_PROJECT_VERSION for compilation."

# Compile OpenFOAM libraries
src/Allwmake $targetType $*

# Compile OpenFOAM applications
applications/Allwmake $targetType $*

# Put utilities in bin to FOAM_APPBIN
mkdir -p "${FOAM_USER_APPBIN}" "${FOAM_USER_LIBBIN}"
for f in bin/*; do
    [ -f "${f}" ] &&
        ln -sf "$(realpath ${f})" "${FOAM_USER_APPBIN}/$(basename ${f})"
done

# Put .env-files in user's platforms
for f in etc/*.env; do
    sed "s|\${WM_PROJECT_VERSION:-dev}|${WM_PROJECT_VERSION}|g" "${f}" >"$FOAM_LIBBIN/../../$(basename ${f})"
done
