#!/bin/sh
cd ${0%/*} || exit 1 # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

NSLOTS="${NSLOTS:-4}"
foamDictionary system/decomposeParDict -entry numberOfSubdomains -set $NSLOTS

# Test engineMeshConfig
runApplication -o predictRemeshInstants
runApplication -o moveSurfaces
runApplication -o engineMeshConfig

# Generate meshes sequentially
for mesh in $(cat constant/meshTimes); do
    generateMesh -cores "$NSLOTS" -mesh "$mesh"
done

# Submit all the mesh jobs to cluster (pseudo-parallel)
# cat constant/meshTimes | xargs -I{} generateMesh -<sge/slurm> (optional) -cores $NSLOTS -mesh {}
#------------------------------------------------------------------------------
