#!/bin/bash
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for compilation
. $WM_DIR/scripts/AllwmakeParseArguments

# Compile utilities
wmake $targetType utilities/engineMeshConfig
wmake $targetType utilities/moveSurfaces
wmake $targetType utilities/predictRemeshInstants
wmake $targetType utilities/reorderPatchesAndFaces

#------------------------------------------------------------------------------