#!/bin/bash
set -e

# This script download the pre-generated GridPro meshes to your hard drive.
# Usage: ./downloadMeshes [coarse|fine]

if [ $# -ne 1 ]; then
    echo "Usage: $0 [coarse|fine]"
    exit 1
fi

if [ "$1" != "coarse" ] && [ "$1" != "fine" ]; then
    echo "Error: Argument must be 'coarse' or 'fine'"
    exit 1
fi

MESH_TYPE="$1"
domain=https://s3.eu-west-1.amazonaws.com/dl.openfoam.org/ICengines/TCC-III

# Check if the meshTimes_$MESH_TYPE file exists
if [ ! -f "meshTimes_$MESH_TYPE" ]; then
    echo "Error: meshTimes_$MESH_TYPE file not found."
    exit 1
fi

times="$(cat meshTimes_$MESH_TYPE | xargs)"

for t in $times; do
    pack="$MESH_TYPE/meshToMesh_$t"
    [ ! -d "$pack/polyMesh" ] && mkdir -p "$MESH_TYPE" && curl "$domain/$MESH_TYPE/meshToMesh_$t.txz" | tar xJf - -C "$MESH_TYPE/"
done

echo -e "\e[32m$MESH_TYPE GridPro meshes are ready for use.\e[0m"
#------------------------------------------------------------------------------