#!/bin/sh
cd ${0%/*} || exit 1 # Run from this directory

# Set number of threads to 4
OMP_NUM_THREADS=4

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

NSLOTS="${NSLOTS:-64}"
foamDictionary system/decomposeParDict -entry numberOfSubdomains -set $NSLOTS

tar -xzf constant/geometry.tar.gz -C constant

# Predict remeshing instants
runApplication -o predictRemeshInstants

# Setup STL surfaces in the predict remesh instants directory
runApplication -o moveSurfaces

# Write blockMeshDict, SnappyHexMeshDict, and meshQualityDict in the instants directory
runApplication -o engineMeshConfig

# Generate meshes sequentially
for mesh in $(cat constant/meshTimes); do
    generateMesh -cores "$NSLOTS" -mesh "$mesh"
done
#------------------------------------------------------------------------------
