#!/bin/sh
cd ${0%/*} || exit 1 # Run from this directory

# Download geometry from confluence if not already present
if [ ! -d constant/geometry ]; then
    echo "Downloading geometry..."
    wget https://confluence.devops.wartsila.com/download/attachments/306362408/geometry.tar.gz
    mkdir -p constant
    tar -xzf geometry.tar.gz -C constant
    rm geometry.tar.gz
    echo "Geometry downloaded and extracted."
fi

#------------------------------------------------------------------------------
