#!/bin/bash
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for compilation
. $WM_DIR/scripts/AllwmakeParseArguments

# Compile libraries
wmake $targetType preProcessing
wmake $targetType searchableSurfaces

#------------------------------------------------------------------------------